---
- name: Maintain Debian 12 VM
  hosts: all
  become: yes
  roles:
    - common
  tasks:
    - name: Ensure the system is updated
      apt:
        update_cache: yes
        upgrade: dist
      register: upgrade_result

    - name: Install essential packages
      apt:
        name: "{{ packages }}"
        state: present

    - name: Clean up unused packages
      apt:
        autoremove: yes
        purge: yes

    - name: Reboot the system if needed
      reboot:
        msg: "Rebooting after updates"
        pre_reboot_delay: 5
      when: upgrade_result.changed

    - name: Set ASCII MOTD
      copy:
        dest: /etc/motd
        src: motd.ascii

    - name: Ensure default directories exist in user's home
      become: false
      file:
        path: "~/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - git
        - code
        - docs
        - temp