SELECT  c."As Of Date"
       ,c."Complaint Id"
--, "Complaint Officer Number"
--, "Tax ID"
--, "Officer Rank Abbreviation At Incident"
       ,c."Officer Rank At Incident"
--, "Officer Command At Incident"
       ,c."Officer Days On Force At Incident"
       ,c."Allegation Record Identity"
       ,c."FADO Type"
       ,c.allegation
       ,c."Victim/Alleged Victim Age Range At Incident"
       ,c."Victim/Alleged Victim Gender"
-- , "Victim / Alleged Victim Race (Legacy)"
-- , "Victim / Alleged Victim Race / Ethnicity"
       ,COALESCE("Victim / Alleged Victim Race (Legacy)","Victim / Alleged Victim Race / Ethnicity") AS "Victim Race"
       ,c."CCRB Allegation Disposition"
       ,c."NYPD Allegation Disposition"
       ,c."Investigator Recommendation"
-- , "CCRB Substantiated Officer Disposition"
-- , "Board Discipline Recommendation"
-- , "Non-APU NYPD Penalty Report Date"
-- , "Officer is_APU"
-- , "APU CCRB Trial Recommended Penalty"
-- , "APU Trial Commissioner Recommended Penalty"
-- , "APU Plea Agreed Penalty"
-- , "APU Case Status"
-- , "APU Closing Date"
-- , "NYPD Officer Penalty"
       ,p."CCRB Substantiated Officer Disposition"
       ,p."Board Discipline Recommendation"
       ,p."NYPD Officer Penalty"
FROM "open-data".civilian_complaint_review_board c
INNER JOIN "open-data".civilian_complaint_review_board_penalties p
ON c."Complaint Id" = p."Complaint Id";