---
- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present
    update_cache: yes

- name: Ensure PostgreSQL service is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Ensure Ansible temp directory exists for postgres
  file:
    path: /var/lib/postgresql/.ansible/tmp
    state: directory
    owner: postgres
    group: postgres
    mode: "0700"
  become: true

- name: Ensure psycopg2 is installed for PostgreSQL modules
  apt:
    name: python3-psycopg2
    state: present
    update_cache: yes
  become: true

- name: Create PostgreSQL user (root workaround)
  shell: |
    sudo -u postgres psql -c "DO \$\$ BEGIN IF NOT EXISTS (SELECT FROM pg_catalog.pg_user WHERE usename = '{{ pg_user }}') THEN CREATE USER {{ pg_user }} WITH PASSWORD '{{ pg_password }}'; END IF; END \$\$;"
  args:
    executable: /bin/bash

- name: Create PostgreSQL database (root workaround)
  shell: |
    sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='{{ pg_database }}'" | grep -q 1 || sudo -u postgres psql -c "CREATE DATABASE {{ pg_database }} OWNER {{ pg_user }};"
  args:
    executable: /bin/bash
